version: '2'
services:
    notesapplication-app:
        image: notesapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://notesapplication-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=NotesApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    notesapplication-mongodb:
        extends:
            file: mongodb.yml
            service: notesapplication-mongodb
